project_id = "wncvvncldryfqqvpmnor"

[functions.ai-interview]
verify_jwt = false

[functions.ai-interview-v2]

[functions.invite-admin]
verify_jwt = true

[functions.generate-pdf]
verify_jwt = true

[functions.send-report]
verify_jwt = false

[functions.get-system-setting]
verify_jwt = false

[functions.signup-supplier]
verify_jwt = true

[functions.parse-regional-pricelist]
verify_jwt = true

[functions.test-postmark]
verify_jwt = false
