project_id = "wncvvncldryfqqvpmnor"

[functions.ai-interview]
verify_jwt = false
import_map = "./import_map.json"

[functions.invite-admin]
verify_jwt = false

[functions.generate-pdf]
verify_jwt = false

[functions.get-system-setting]
verify_jwt = false

[functions.signup-supplier]
verify_jwt = false

[functions.parse-regional-pricelist]
verify_jwt = true